In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
%pip install openpyxl

Requirement already satisfied: openpyxl in /opt/conda/lib/python3.8/site-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.8/site-packages (from openpyxl) (1.1.0)
Note: you may need to restart the kernel to use updated packages.

In [15]:
# Read in the Excel file for 2017-18 Pharr SJ and replace any * or - values with NaN.
PSJ17 = pd.read_excel('PharrSJ-17.xlsx').replace(['*','-'],'NaN')

# Change all numerical columns to float (the *s were 'objects' and math with NaN values can be handled if they're floats).
for column in PSJ17:
    if column != 'Test' and column != 'Level' and column != 'District':
        PSJ17[column] = PSJ17[column].astype(float)

# Rename some of the columns to make them easier to read.
PSJ17 = PSJ17.rename(columns={'African\nAmerican':'Afr Am','American\nIndian':'Am Ind','Pacific\nIslander':'Pac Isl',
                                'Two or\nMore\nRaces':'2+ Race','Special\nEd':'Spec Ed','Econ\nDisadv':'Econ Disad'})

# Split the dataframe into 'labels' and 'numbers', convert the numbers to represent only the percentage in each category.
# Originally, the percentages in the spreadsheets represent the students that hit that level *or above*.
work = PSJ17.drop(PSJ17.columns[[0,1,2,3,4]], axis=1)
info = PSJ17.drop(PSJ17.columns[[5,6,7,8,9,10,11,12,13,14,15]], axis=1)
for row in range(24):
    if ((row-2)%8) == 0:
        work.loc[row] = work.loc[row] - work.loc[row+2]
    elif ((row+4)%8) == 0:
        work.loc[row] = work.loc[row] - work.loc[row+2]

# Rejoin the info with the numbers to make one dataframe, sorted by year.
# Once everyone's done, we'll concatenate these into one dataframe, sorted by district, then year, then grade level.
PSJ17 = info.join(work).sort_values(by=['Year','Grade'],ascending=True).reset_index(drop=True)
PSJ17

,District,Year,Grade,Test,Level,State,All,Afr Am,Hispanic,White,Am Ind,Asian,Pac Isl,2+ Race,Spec Ed,Econ Disad
0,Pharr-SJ,2017.0,3.0,Reading,Not Approaching Grade Level,27.0,27.0,NaN,26.0,NaN,NaN,NaN,NaN,NaN,49.0,28.0
1,Pharr-SJ,2017.0,3.0,Reading,Approaches Grade Level,73.0,73.0,NaN,74.0,NaN,NaN,NaN,NaN,NaN,51.0,72.0
2,Pharr-SJ,2017.0,3.0,Reading,Meets Grade Level,22.0,23.0,NaN,23.0,NaN,NaN,NaN,NaN,NaN,-10.0,20.0
3,Pharr-SJ,2017.0,3.0,Reading,Masters Grade Level,29.0,27.0,NaN,27.0,NaN,NaN,NaN,NaN,NaN,14.0,25.0
4,Pharr-SJ,2017.0,3.0,Mathematics,Not Approaching Grade Level,-26.0,-31.0,NaN,-31.0,NaN,NaN,NaN,NaN,NaN,3.0,-28.0
5,Pharr-SJ,2017.0,3.0,Mathematics,Approaches Grade Level,77.0,79.0,NaN,79.0,NaN,NaN,NaN,NaN,NaN,58.0,78.0
6,Pharr-SJ,2017.0,3.0,Mathematics,Meets Grade Level,49.0,52.0,NaN,52.0,NaN,NaN,NaN,NaN,NaN,39.0,50.0
7,Pharr-SJ,2017.0,3.0,Mathematics,Masters Grade Level,26.0,29.0,NaN,29.0,NaN,NaN,NaN,NaN,NaN,23.0,27.0
8,Pharr-SJ,2017.0,6.0,Reading,Not Approaching Grade Level,31.0,49.0,NaN,49.0,NaN,NaN,NaN,NaN,NaN,NaN,52.0
9,Pharr-SJ,2017.0,6.0,Reading,Approaches Grade Level,69.0,51.0,NaN,51.0,NaN,NaN,NaN,NaN,NaN,NaN,48.0
10,Pharr-SJ,2017.0,6.0,Reading,Meets Grade Level,13.0,-17.0,NaN,-18.0,NaN,NaN,NaN,NaN,NaN,NaN,-22.0
11,Pharr-SJ,2017.0,6.0,Reading,Masters Grade Level,18.0,8.0,NaN,8.0,NaN,NaN,NaN,NaN,NaN,NaN,6.0
12,Pharr-SJ,2017.0,6.0,Mathematics,Not Approaching Grade Level,-19.0,18.0,NaN,18.0,NaN,NaN,NaN,NaN,NaN,51.0,22.0
13,Pharr-SJ,2017.0,6.0,Mathematics,Approaches Grade Level,76.0,61.0,NaN,61.0,NaN,NaN,NaN,NaN,NaN,34.0,59.0
14,Pharr-SJ,2017.0,6.0,Mathematics,Meets Grade Level,43.0,21.0,NaN,21.0,NaN,NaN,NaN,NaN,NaN,15.0,19.0
15,Pharr-SJ,2017.0,6.0,Mathematics,Masters Grade Level,18.0,6.0,NaN,6.0,NaN,NaN,NaN,NaN,NaN,6.0,5.0
16,Pharr-SJ,2017.0,9.0,English I,Not Approaching Grade Level,36.0,48.0,NaN,48.0,NaN,NaN,NaN,NaN,NaN,80.0,51.0
17,Pharr-SJ,2017.0,9.0,English I,Approaches Grade Level,64.0,52.0,NaN,52.0,NaN,NaN,NaN,NaN,NaN,20.0,49.0
18,Pharr-SJ,2017.0,9.0,English I,Meets Grade Level,-40.0,-53.0,NaN,-53.0,NaN,NaN,NaN,NaN,NaN,-41.0,-55.0
19,Pharr-SJ,2017.0,9.0,Algebra I,Masters Grade Level,17.0,16.0,NaN,16.0,NaN,NaN,NaN,NaN,NaN,46.0,17.0
20,Pharr-SJ,2017.0,9.0,Algebra I,Not Approaching Grade Level,57.0,56.0,NaN,56.0,NaN,NaN,NaN,NaN,NaN,44.0,56.0
21,Pharr-SJ,2017.0,9.0,Algebra I,Approaches Grade Level,48.0,51.0,NaN,51.0,NaN,NaN,NaN,NaN,NaN,22.0,48.0
22,Pharr-SJ,2017.0,9.0,Algebra I,Meets Grade Level,26.0,28.0,NaN,28.0,NaN,NaN,NaN,NaN,NaN,10.0,27.0
23,Pharr-SJ,2017.0,9.0,Algebra I,Masters Grade Level,48.0,42.0,41.0,42.0,48.0,NaN,78.0,NaN,NaN,24.0,40.0